config/routes.rb
Resume::Application.routes.draw do
  get "about/index"

  get "resume/index"

  resources :projects

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :long_description, :short_description, :subtitle, :title, :url
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @projects = Project.all
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, :notice => 'Project was successfully created.' }
        format.json { render :json => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, :notice => 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  # GET /projects/gallery
  # GET /projects/gallery.json
  def gallery
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @projects }
    end
  end

end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/about/index.html.erb
<div class="row">
  <div class="span8">

    <div class="hero-unit">
      <h1>Welcome!</h1>
      <p>Hello there! I'm Rob Grmek, a resident of the sunny Okanagan in British Columbia, and this website holds my public resume as well as a listing of some of my projects which are publicly available for demonstration purposes.</p>
      <p>
        <a class="btn btn-primary btn-large">
          <i class="icon-list-alt icon-white"></i>
          View resume
        </a>
        <a class="btn btn-success btn-large">
          <i class="icon-folder-open icon-white"></i>
          View projects
        </a>
        <a class="btn btn-info btn-large" href="mailto:rgrmek@gmail.com">
          <i class="icon-envelope icon-white"></i>
          Contact me
        </a>
      </p>
    </div>
  </div>
  <div class="span4">
    <div class="page-header">
      <h1>About Me</h1>
    </div>
      <p> 
        Aspiring to become a software engineer, I have received my Bachelor of Computer Information Systems (BCIS) from Okanagan College in 2010. Over the course of my education, I have studied various object-oriented analysis, design and programming techniques and languages as well as languages from other programming paradigms such as PL/SQL and Scheme. I have put these techniques into practice by implementing projects on time and within budget while meeting the customer&rsquo;s requirements using agile software development methodologies such as Extreme Programming (XP) and other software development process frameworks such as the Rational Unified Process (RUP). Always eager to learn, I am self-motivated and always aspire to be professional in every aspect of my life.
      </p> 
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rob Grmek</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Rob Grmek</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "About", :controller => "about", :action => "index" %></li>
          <li><%= link_to "Resume", :controller => "resume", :action => "index" %></li>
          <li><%= link_to "Projects", projects_path %></li>
          <!--
          <li class="dropdown">
            <%= link_to content_tag(:b, '', :class => "caret"), projects_path, :class => "dropdown-toggle", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu">
              <li><%= link_to "Project 1", projects_path %></li>
              <li><%= link_to "Project 2", projects_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Projects
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Project 1", projects_path %></li>
              <li><%= link_to "Project 2", projects_path %></li>
            </ul>
          </li>
          -->
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
<%= yield %>
  </div>
</div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :subtitle, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subtitle, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :short_description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :short_description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :long_description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :long_description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%- model_class = @project.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/projects/gallery.html.erb
<%- model_class = Project.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:subtitle) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, project_path(project) %></td>
        <td><%= project.title %></td>
        <td><%= project.subtitle %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.delete")),
                      project_path(project),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Subtitle</th>
    <th>Short description</th>
    <th>Long description</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.title %></td>
    <td><%= project.subtitle %></td>
    <td><%= project.short_description %></td>
    <td><%= project.long_description %></td>
    <td><%= project.url %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<%- model_class = @project.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<ul class="breadcrumb">
  <li>
    <%= link_to "Projects", projects_path %> <span class="divider">/</span>
  </li>
  <li class="active"><%= @project.title %></li>
</ul>
<div class="row">
  <div class="span3">
    <div class="well" style="padding: 8px 0;">
      <ul class="nav nav-list">
        <li class="nav-header">
          Projects
        </li>
        <% @projects.each do |item| %>
        <li>
          <%= link_to item.title, :controller => "projects", :action => "show", :id => item.id %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="span9">
    <%- model_class = @project.class -%>
    <div class="page-header">
      <h1><%= @project.title%></h1>
    </div>

    <p>
      <strong><%= model_class.human_attribute_name(:subtitle) %>:</strong><br>
      <%= @project.subtitle %>
    </p>
    <p>
      <strong><%= model_class.human_attribute_name(:short_description) %>:</strong><br>
      <%= @project.short_description %>
    </p>
    <p>
      <strong><%= model_class.human_attribute_name(:long_description) %>:</strong><br>
      <%= @project.long_description %>
    </p>
    <p>
      <strong><%= model_class.human_attribute_name(:url) %>:</strong><br>
      <%= @project.url %>
    </p>

    <!--
    <div class="form-actions">
      <%= link_to t('.back', :default => t("helpers.links.back")),
                  projects_path, :class => 'btn'  %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_project_path(@project), :class => 'btn' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  project_path(@project),
                  :method => 'delete',
                  :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                  :class => 'btn btn-danger' %>
    </div>
    -->

  </div>
</div>

app/views/resume/index.html.erb
<div class="page-header">
  <h1>Goal</h1> 
</div>
<div class="well">
  <p>To become an accomplished software engineer while continuing to design and deliver quality systems.</p> 
</div>

<div class="page-header">
  <h1>Credentials</h1> 
</div>
<div class="well">
  <p> 
    <b>Bachelor of Computer Information Systems, 2008-2010</b> 
    <br /> 
    Okanagan College, Kelowna, BC
    <br /> 
    Major: Software Design and Development
    <br /> 
    Major: Database Systems Architecture and Administration
    <br /> 
    Honors: Bachelor of CIS Medal, Graduated with Distinction
  </p> 
  <p> 
    <b>Computer Information Systems Diploma, 2006-2008</b> 
    <br /> 
    Okanagan College, Kelowna, BC
    <br /> 
    Major: Software Development
    <br /> 
    Honors: Graduated with Distinction
  </p> 
</div>


<div class="page-header">
  <h1>Related Experience</h1> 
</div>
<div class="well">
  <p> 
    <b>Software Developer</b> 
    <br /> 
    Sun-Rype Products Ltd., Kelowna, BC; 2010-Present
  </p> 
  <ul> 
    <li> 
      Developed tailor made web applications for use within the organization's intranet and extranet using the ASP.NET WebForms and MVC frameworks
    </li> 
    <li> 
      Provided further automation within business processes and promoted increased business collaboration within SharePoint via custom workflows, event receivers and web parts
    </li> 
    <li> 
      Maintained, refactored and extended the functionality of existing projects to meet changing requirements
    </li> 
  </ul> 
  <p> 
    <b>Project Manager and Team Lead</b> 
    <br /> 
    Okanagan College, Kelowna, BC; 2009-2010
  </p> 
  <ul> 
    <li> 
      Designed and developed an automatic telescope control system using the agile software development methodology of Extreme Programming and later the Rational Unified Process methodology
    </li> 
    <li> 
      Achieved process automation for scheduling a Meade telescope to celestial coordinates or objects at future dates and then to take pictures of that area using a Canon 30D digital camera integrated with the systems
    </li> 
    <li> 
      Implemented further functionality for separate mobile views, authentication and authorization as well as adding SSL encryption to improve data confidentiality
    </li> 
    <li> 
      View a limited-functionality version for demonstration purposes at:
      <a href='http://stargazer.heroku.com' title='Stargazer - Automatic Telescope Control System'>http://stargazer.heroku.com</a> 
    </li> 
  </ul> 
  <p> 
    <b>Research Assistant - Supervisor: Youry Khmelevsky</b> 
    <br /> 
    Okanagan College, Kelowna, BC; 2009-2010
  </p> 
  <ul> 
    <li>Assisted in writing research grant proposals as well as research papers and articles on topics such as cloud computing and RFID applications</li> 
    <li>Co-published a research paper on automating inventory tracking within an organization's supply chain through the use of low cost mobile technology</li> 
    <li>Contributed in configuring the Computer Science department's rack-mounted servers hosted at the college</li> 
    <li>Implemented a research project which was to create custom barcode reading software using a Java MIDlet program and a Ruby on Rails web application</li> 
  </ul> 
  <p> 
    <b>Research Assistant - Supervisor: Heather Banham</b> 
    <br /> 
    Okanagan College, Kelowna, BC; 2008-2010
  </p> 
  <ul> 
    <li>Assisted in the implementation of the $1,000,000 project dubbed Building Small Business Human Resources, funded by the Canadian government</li> 
    <li>Developed and maintained the database-driven web portal, as a part of a team of other students, using Oracle Application Express (APEX)</li> 
    <li>Automated processes for tasks such as URL checking to improve maintainability</li> 
    <li> 
      View the live production version at:
      <a href='http://bsbhr.org' title='Building Small Business HR Resource Guide'>http://bsbhr.org</a> 
    </li> 
  </ul> 
</div>
          
<div class="page-header">
  <h1>Awards</h1> 
</div>
<div class="well">
  <p> 
    <b>BCIS Award</b> 
    <br /> 
    Okanagan College
    <br /> 
    Awarded in June 2010 for having the highest graduating average of any student in the BCIS program
  </p> 
  <p> 
    <b>Academic Achievement Scholarship</b> 
    <br /> 
    Okanagan College
    <br /> 
    Awarded for Winter and Fall 2009 semesters
  </p> 
  <p> 
    <b>Dean's List Certificates</b> 
    <br /> 
    Okanagan College
    <br /> 
    Awarded each semester from Fall 2006 to Winter 2010
  </p> 
</div>


<div class="page-header">
  <h1>Applied Skills</h1> 
</div>
<div class="well">
  <p> 
    <b>Programming Languages</b> 
  </p> 
  <ul> 
    <li>Proficient in: Ruby, Java, Visual Basic, PL/SQL, HTML, XML</li> 
    <li>Experience with: PHP, Perl, C++, C#, Scheme, JavaScript</li> 
  </ul> 
  <p> 
    <b>PC Software</b> 
    <br /> 
    Experienced with the following:
  </p> 
  <ul> 
    <li>Web Frameworks: Ruby on Rails, Oracle Application Express, Java Enterprise Edition, ASP.NET WebForms and MVC</li> 
    <li>RDBMS: Oracle, SQL Server, MySQL, SQLite</li> 
    <li>OS: Windows (XP, Server, Vista, 7), Linux (Ubuntu, Fedora), Unix</li> 
    <li>Versioning Control Systems: Git, Team Foundation Server, CVS, SVN</li> 
    <li>Office Suites: Microsoft Office, OpenOffice.org</li> 
  </ul> 
  <p> 
    <b>Areas of Knowledge</b> 
    <br /> 
    Practical applications of the following skills and areas of knowledge:
  </p> 
  <ul> 
    <li>Project management in software development</li> 
    <li>Agile software development methodologies and the Rational Unified Process (RUP)</li> 
    <li>Applying software patterns</li> 
    <li>Search engine optimization techniques</li> 
    <li>Database design and administration</li> 
    <li>Query optimization techniques</li> 
    <li>Object-oriented systems analysis and design</li> 
    <li>Computer networking</li> 
  </ul> 
</div>